from django.urls import path 
from .views import (
    HomeView,
    ServiceView,
    AboutView,
    ContactView,
    FAQView,
    PrivacyPolicyView,
    FundingPolicyView,
    WithdrawalPolicyView,
    TermsView,
    DashboardView,
    ExchangeView,
    ActivateCardView,
    LoanFormView,
    TicketFormView,
    TicketListView,
    LoanListView,
    TransactionReportView,
    DPSSchemesView,
    DPSSchemePlanView,
    ApplyFixedDepositView,
    AutomaticDepositView,
    ManualDepositView,
    WithdrawalFormView,
    FixedDepositsHistoryView,
    CardListView,
    WalletFormView,
    WalletListView,
    success_view,
    cancel_view,
)

urlpatterns = [
    path('', HomeView.as_view(), name='homepage'),
    path('customer/exchange-currency/', ExchangeView.as_view(), name='exchange-currency'),
    path('customer/dashboard/', DashboardView.as_view(), name='dashboard'),
    path('customer/activate-account/', ActivateCardView.as_view(), name='activate-card'),
    path('customer/apply-loan/', LoanFormView.as_view(), name='apply-loan'),
    path('customer/create-ticket/', TicketFormView.as_view(), name='create-ticket'),
    path('customer/tickets/', TicketListView.as_view(), name='tickets'),
    path('customer/loans/', LoanListView.as_view(), name='loans'),
    path('customer/transaction-report/', TransactionReportView.as_view(), name='transaction-report'),
    path('customer/dpsschemes/plans/', DPSSchemePlanView.as_view(), name='dps-schemes-plan'),
    path('customer/dpsschemes/my-dps/', DPSSchemesView.as_view(), name='my-dps'),
    path('customer/fixed-deposit/apply/', ApplyFixedDepositView.as_view(), name='fixed-deposit'),
    path('customer/automatic-deposit/', AutomaticDepositView.as_view(), name='automatic-deposit'),
    path('customer/manual-methods/', ManualDepositView.as_view(), name='manual-methods'),
    path('customer/withdraw/', WithdrawalFormView.as_view(), name='withdrawal'),
    path('customer/fixed-deposit/history/', FixedDepositsHistoryView.as_view(), name='history'),
    path('customer/account-activation/success/', success_view, name='payments-success'),
    path('customer/account-activation/cancel/', cancel_view, name='payments-cancel'),
    path('customer/active-cards/', CardListView.as_view(), name='active-cards'),
    path('customer/wallets/add/', WalletFormView.as_view(), name='add-wallet'),
    path('customer/wallets/', WalletListView.as_view(), name='my-wallets'),
    path('services/', ServiceView.as_view(), name='services'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('faq/', FAQView.as_view(), name='faq'),
    path('privacy-policy/', PrivacyPolicyView.as_view(), name='privacy-policy'),
    path('terms/', TermsView.as_view(), name='terms'), 
    path('withdrawal-policy/', WithdrawalPolicyView.as_view(), name='withdrawal-policy'),
    path('funding-policy/', FundingPolicyView.as_view(), name='funding-policy'),
]
