# Generated by Django 4.2.3 on 2023-08-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_account_account_holder_alter_account_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='euro_balance',
        ),
        migrations.AddField(
            model_name='account',
            name='inr_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='account',
            name='usd_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
