# Generated by Django 4.2.3 on 2023-08-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_balance_account_euro_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='euro_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='inr_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='usd_balance',
        ),
        migrations.AddField(
            model_name='account',
            name='euro_account',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='account',
            name='inr_account',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='account',
            name='usd_account',
            field=models.JSONField(default=dict),
        ),
    ]
