# Generated by Django 4.2.3 on 2023-08-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_account_currency_remove_account_euro_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DollarAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EuroAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RupeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('value', models.FloatField()),
            ],
        ),
    ]
