# Generated by Django 4.2.3 on 2023-08-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_dollaraccount_euroaccount_rupeeaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='currency',
        ),
        migrations.AlterField(
            model_name='account',
            name='euro_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.euroaccount'),
        ),
        migrations.AlterField(
            model_name='account',
            name='inr_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.rupeeaccount'),
        ),
        migrations.AlterField(
            model_name='account',
            name='usd_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dollaraccount'),
        ),
        migrations.AlterField(
            model_name='dollaraccount',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='euroaccount',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rupeeaccount',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
