# Generated by Django 4.2.3 on 2023-08-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_loan_currency_alter_account_euro_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='euro_account',
            field=models.FloatField(default=0, verbose_name='Euro Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='inr_account',
            field=models.FloatField(default=0, verbose_name='Rupee Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='usd_account',
            field=models.FloatField(default=0, verbose_name='Dollar Account'),
        ),
        migrations.DeleteModel(
            name='DollarAccount',
        ),
        migrations.DeleteModel(
            name='EuroAccount',
        ),
        migrations.DeleteModel(
            name='RupeeAccount',
        ),
    ]
