# Generated by Django 4.2.3 on 2023-08-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_account_euro_account_alter_account_inr_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='currency',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
