# Generated by Django 4.2.3 on 2023-08-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_loan_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='payment_date',
            new_name='proposed_payment_date',
        ),
    ]
