# Generated by Django 4.2.3 on 2023-08-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_payment_date_loan_proposed_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('INR', 'INR')], default='USD', max_length=15),
        ),
    ]
