# Generated by Django 4.2.3 on 2023-08-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_loan_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.FloatField(),
        ),
    ]
