# Generated by Django 4.2.3 on 2023-08-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='identity',
            field=models.FileField(upload_to='files/identity'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(upload_to='files/tickets'),
        ),
    ]
