# Generated by Django 4.2.3 on 2023-08-27 19:49

import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_contact_created_at_contact_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='proposed_payment_date',
            field=models.DateField(validators=[dashboard.validators.validate_proposed_payment_date]),
        ),
    ]
