# Generated by Django 4.2.3 on 2023-11-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_activationcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcard',
            name='card_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='activationcard',
            name='valid_thru',
            field=models.DateField(null=True),
        ),
    ]
