# Generated by Django 4.2.3 on 2023-11-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_activationcard_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcard',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='activationcard',
            name='valid_thru',
            field=models.DateField(blank=True, null=True),
        ),
    ]
