# Generated by Django 4.2.3 on 2023-11-11 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0020_alter_activationcard_card_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('crypto', models.CharField(choices=[('BTC', 'BTC'), ('USDT (TRC20)', 'USDT (TRC20)')], max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('crypto', 'address')},
            },
        ),
    ]
