# Generated by Django 4.2.3 on 2023-11-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_wallet_created_at_wallet_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
