# Generated by Django 4.2.3 on 2023-11-11 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_cryptowithdrawal_transaction_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowithdrawal',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.wallet'),
        ),
    ]
