# Generated by Django 4.2.3 on 2024-01-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_cryptowithdrawal_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loan_product',
            new_name='loan_type',
        ),
        migrations.AddField(
            model_name='loan',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='employer_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='employer_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='experience',
            field=models.CharField(blank=True, choices=[('0-1 Year', '0-1 Year'), ('1-2 Years', '1-2 Years'), ('3-4 Years', '3-4 Years'), ('5+ Years', '5+ Years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='mortgage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='street_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
