# Generated by Django 4.2.3 on 2024-01-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_rename_loan_product_loan_loan_type_loan_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowithdrawal',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('INR', 'INR')], default='USD', max_length=10),
        ),
    ]
