# Generated by Django 4.2.3 on 2024-01-17 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_cryptowithdrawal_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowithdrawal',
            name='withdrawal_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
