# Generated by Django 4.2.3 on 2024-02-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['-published_at']},
        ),
        migrations.AddField(
            model_name='jobpost',
            name='benefits',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=255, null=True),
        ),
    ]
