# Generated by Django 4.2.3 on 2024-02-21 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_alter_jobpost_options_jobpost_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Part Time/Full Time', 'Part Time/Full Time')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('current_job', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField()),
                ('resume', models.FileField(upload_to='files/resumes')),
                ('cover_letter', models.TextField()),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.jobpost')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
