# Generated by Django 4.2.3 on 2024-02-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_alter_jobpost_type_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
