# Generated by Django 4.2.3 on 2024-02-22 20:08

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_alter_jobapplication_cover_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDMELogins',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employment.jobpost'),
        ),
    ]
