# Generated by Django 4.2.3 on 2024-02-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0005_idmelogins_alter_jobapplication_job_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.jobpost'),
        ),
    ]
