# Generated by Django 4.2.3 on 2024-02-23 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0006_alter_jobapplication_job_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
