# Generated by Django 4.2.3 on 2024-02-25 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0007_alter_jobpost_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
