# Generated by Django 4.2.3 on 2024-03-14 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0008_alter_jobpost_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='driver_license',
            field=models.FileField(default=django.utils.timezone.now, upload_to='files/driver_licence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ssn',
            field=models.FileField(default=django.utils.timezone.now, upload_to='files/ssn'),
            preserve_default=False,
        ),
    ]
