# Generated by Django 4.2.3 on 2024-03-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0009_jobapplication_driver_license_jobapplication_ssn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='ssn',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='availability',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='driver_license',
            field=models.FileField(upload_to='files/drivers_licence'),
        ),
    ]
