# Generated by Django 4.2.3 on 2024-03-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0010_remove_jobapplication_ssn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ssn',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
