# Generated by Django 4.2.3 on 2024-03-14 20:11

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0011_jobapplication_ssn'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='files/drivers_licence')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.jobapplication')),
            ],
        ),
    ]
