# Generated by Django 4.2.3 on 2024-03-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0012_driverlicense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlicense',
            name='application',
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='name',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
