# Generated by Django 4.2.3 on 2024-03-14 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0013_remove_driverlicense_application_driverlicense_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlicense',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='job',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
