# Generated by Django 4.2.3 on 2024-03-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0014_driverlicense_applied_at_driverlicense_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='driver_license',
            new_name='driver_license_back',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='driver_license_front',
            field=models.FileField(default=1, upload_to='files/drivers_licence'),
            preserve_default=False,
        ),
    ]
