# Generated by Django 4.2.3 on 2024-03-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0015_rename_driver_license_jobapplication_driver_license_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='nationality',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
