# Generated by Django 4.2.3 on 2024-03-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0016_jobapplication_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='gender',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
