# Generated by Django 4.2.3 on 2024-04-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0017_jobapplication_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='ssn',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
